services:
  redis:
    container_name: redis
    image: redis:7
  bot:
    container_name: telegram-bot
    hostname: telegram-bot
    build:
      context: ../services/bot
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - BOT_TOKEN
      - REDIS_HOST
      - LOG_LVL
      - LOG_PATH
    ports:
      - "8000:8000"
    volumes:
      - ../services/logs:/app/logs
# For some unknown to me reason gives warning...
#    volumes:
#      - ../services/bot:/app
    develop:
      watch:
        - action: sync
          path: ../services/bot/
          target: /app
          ignore:
            # Ignores everything but python files 
            - "!**/*.py"

        - action: rebuild
          path: Dockerfile

        - action: restart
          path: ../services/bot/
  generator:
    container_name: generator
    hostname: generator
    depends_on:
      - redis
    build:
      context: ../services/generator/
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=${REDIS_HOST}
