services:
  redis:
    container_name: redis
    image: redis:7
    networks:
      - monitoring

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  bot:
    container_name: telegram-bot
    hostname: telegram-bot
    networks:
      - monitoring
    build:
      context: ../services/bot
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - BOT_TOKEN
      - REDIS_HOST
      - LOG_LVL
      - LOG_PATH
    ports:
      - "8000:8000"
    volumes:
      - ../services/logs:/app/logs
    develop:
      watch:
        - action: sync
          path: ../services/bot/
          target: /app
          ignore:
            # Ignores everything but python files 
            - "!**/*.py"

        - action: rebuild
          path: Dockerfile

        - action: restart
          path: ../services/bot/
  generator:
    container_name: generator
    hostname: generator
    networks:
      - monitoring
    build:
      context: ../services/generator/
      dockerfile: Dockerfile
    depends_on:
      - redis
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST
    volumes:
      - ./core:/core

  template_engine:
    container_name: template_engine
    networks:
      - monitoring
    build:
      context: ../services/template_engine/
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - REDIS_HOST
    volumes:
      - ../services/logs:/app/logs
    develop:
      watch:
        - action: sync
          path: ../services/template_engine/
          target: /app
          ignore:
            # Ignores everything but python files
            - "!**/*.py"

        - action: rebuild
          path: Dockerfile

        - action: restart
          path: ../services/template_engine/

networks:
  monitoring:
